# Generated by Django 5.2 on 2025-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_useranswer_short_answer_alter_useranswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
