# Generated by Django 5.2 on 2025-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_quiz_slide_quiz_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
