# Generated by Django 5.2 on 2025-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
