# Generated by Django 5.2 on 2025-04-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_blogpost_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='species_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.PositiveIntegerField()),
                ('food_rate', models.FloatField()),
                ('reproduction_rate', models.FloatField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.species')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=50)),
                ('species_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_a', to='myapp.species')),
                ('species_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_b', to='myapp.species')),
            ],
        ),
    ]
