# Generated by Django 5.2 on 2025-04-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_species_population_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='species',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
